---
abstract: 'flexible, OO, asynchronous process spawning and management'
author:
  - 'Jonathan Rockway C<< <jrockway@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Subprocess
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  AnyEvent: 5.2
  Event::Join: 0.02
  IO::Pty: 0
  Moose: 0.91
  MooseX::Role::Parameterized: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0.19
  POSIX: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
